name: 🤔 Ask question
description: Consider using discussions for simple usage questions instead of issues.
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Kindly note

        We encourage you to use discussions instead of asking about usage in Github issues.
        It's preferable to discuss larger matters here.
  - type: textarea
    id: question-description
    attributes:
      label: Describe your question
      description: A clear and concise description is welcome.
      placeholder: Describe question
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Platform and version and other information that may be helpful.
      render: Shell
      placeholder: System information
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Remember to follow the community guidelines and be friendly.
          required: true
